#!/bin/bash

# Usage:
#
# To enable bash <tab> completion for trailmap, add the following line (minus the
# leading #, which is the bash comment character) to your ~/.bashrc file:
#
# eval "$(trailmap --completion=bash)"

# Enable bash autocompletion.
function _trailmap_completions() {
  # The currently-being-completed word.
  local cur="${COMP_WORDS[COMP_CWORD]}"
  #Grab tasks
  local compls=$(trailmap --tasks-simple)
  # Tell complete what stuff to show.
  COMPREPLY=($(compgen -W "$compls" -- "$cur"))
}

complete -o default -F _trailmap_completions trailmap